package tsi.too.grade_control;

public interface Constants {
	String GRADES_CONTROLLER = "Controle de notas";
	String REGISTER_STUDENT = "Cadastrar aluno";
	String SEARCH_STUDENT = "Pesquisar aluno";
	String NO_STUDENTS_REGISTERED = "Não há alunos registrados";
	String SEARCH_DISCIPLINE = "Pesquisar disciplina";
	String UPDATE_STUDENT_DATA = "Alterar dados do aluno";
	String UPDATE_ANOTHER_GRADE = "Alterar outra nota?";
	String RECORD_UPDATED_SUCCESSFULLY = "Registro atualizado com sucesso";
	String STUDENT_NOT_ENROLLED_IN_THIS_DISCIPLINE = "Aluno nao cadastrado nesta disciplina";
	String UPDATE_GRADES = "Alterar notas";
	String DISCIPLINE_NOTE_FOUND = "Disciplina não encontrada";
	String DELETE_STUDENT = "Apagar aluno";
	String REPORT = "Relatório";
	String EXIT = "Sair";
	String REGISTRATION_NUMBER = "Matrícula";
	String REGISTRATION_NUMBER_CANOT_BE_BLANK = "Matrícula não pode ficar em branco";
	String INVALID_REGISTRATION_NUMBER = "Matrícula inválida";
	String REGISTRATION_ALREADY_REGISTERED = "Matrícula ja registrada";
	String NAME_ALREADY_REGISTERED = "Nome já registrado";
	String NAME = "Nome";
	String NAME_CANNOT_BE_BLANK = "Nome não pode ser vazio";
	String COURSE = "Curso";
	String COURSE_CANNOT_BE_BLANK = "Curso não pode ser vazio.";
	String GRADE = "Nota";
	String GRADE_MUST_BE_BETWEEN_ZERO_AND_TEN = "Nota deve ser entre 0 e 10";
	String STUDENT_ALREADY_ENROLLED_IN_THIS_DISCIPLINE = "Aluno ja matriculado nesta disciplina";
	String STUDENT_NOT_FOUND = "Aluno não encontrado.";
	String DISCIPLINES = "Disciplinas";
	String STUDENT_DATA = "Dados do aluno";
	String ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_STUDENT = "Tem a certeza de que deseja remover este aluno?";
	String STUDENT_SUCCESSFULY_DELETED = "Aluno removido com sucesso";
	String STUDENT_NAME_OR_REGISTRATION = "Nome ou matrícula do aluno";
	String STUDENT_NAME = "Nome do aluno";
	String DISCIPLINE_NAME = "Nome da disciplina";
	String THIS_FIELD_CANNOT_BE_EMPTY = "Este campo não pode ser vazio";
	String THE_STUDENT_IS_NOT_ENROLLED_ON_THIS_SUBJECT = "O aluno %s não está matriculado nesta disciplina.";
	String DISCIPLINE_ENROLLMENT = "Registro em disciplinas.";
	String STUDENT_SUCCESSFULY_REGISTERED = "Aluno registrado com sucesso.";
	String STUDENT_REGISTRATION = "Registro de aluno.";
	String APPROVED = "Aprovado";
	String REPROVED = "Reprovado";
	String RESUME = "Resumo";
	String NUMBER_OF_STUDENTS = "Número de alunos";
	String NUMBER_OF_APPROVED = "Número de aprovados";
	String NUMBER_OF_REPROVEDS = "Número de reprovados";
	String PERCENTAGE_OF_APPROVED = "Percentual de aprovados";
	String PERCENTAGE_OF_REPROVED = "Percentual de reprovados";
	String NO_DATA_FOUND = "Nenhum dado encontrado";
	String ENROLL_IN_ANOTHER_DISCIPLINE = "Inscrever em outra disciplina?";
	String STUDENT_MUST_BE_ENROLLED_IN_A_DISCIPLINE_AT_LEAST_CANCEL_REGISTRATION = "O aluno deve estar inscrito em pelo menos uma disciplina para realizar o registro.\n\n"
			+ "Deseja CANCELAR o registro?";
	String NEW_STUDENT_NAME = "Novo nome do aluno";
	String YOUR_CHANGES_WILL_BE_DISCARDED_ARE_YOU_SURE_YOU_WANT_TO_CANCEL = "Suas alterações serao descartadas, tem certeza que deseja cancelar?";
}